---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--generic-user-home
  labels:
    type: local
spec:
  storageClassName: ${namespace}--generic-user-home
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${generic_user_home}"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--local-home
  labels:
    type: local
spec:
  storageClassName: ${namespace}--local-home
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${local_home}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--jupyter-home
  labels:
    type: local
spec:
  storageClassName: ${namespace}--jupyter-home
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${jupyter_home}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--gpfs
  labels:
    type: local
spec:
  storageClassName: ${namespace}--gpfs
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /gpfs/

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--nfs
  labels:
    type: local
spec:
  storageClassName: ${namespace}--nfs
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfs/

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--scratch
  labels:
    type: local
spec:
  storageClassName: ${namespace}--scratch
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /scratch/

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--tmp
  labels:
    type: local
spec:
  storageClassName: ${namespace}--tmp
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/


---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--lsst-data
  labels:
    type: local
spec:
  storageClassName: ${namespace}--lsst-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${lsst_data}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--lsst-home
  labels:
    type: local
spec:
  storageClassName: ${namespace}--lsst-home
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${lsst_home}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--cdms-data
  labels:
    type: local
spec:
  storageClassName: ${namespace}--cdms-data
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ${cdms_data}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--cdms-home
  labels:
    type: local
spec:
  storageClassName: ${namespace}--cdms-home
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${cdms_home}
